language: php

php:
  - 5.5
  - 5.6
  - '7'
  - hhvm
  - nightly

before_script: composer self-update && composer install

script: vendor/bin/phpunit --coverage-text --debug --verbose

notifications:
  email:
    - miroshnik1992@gmail.com
